measure API execute time seen from guestlib
utcs-scea/ava pull request #166
Opened 2021-06-14 21:30 UTC by photoszzt

Signed-off-by: Zhiting Zhu <zhitingz@cs.utexas.edu>

## Description

## How has this been tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Document update (this change is mainly a documentation update)

## Checklist:

- [ ] My code passes format and lint checks.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generate no new warnings.
- [ ] I have tested my code with a reasonable workload.
- [ ] My code **may break** some other features.

2021-06-14 22:33 UTC, photoszzt commented
The parse script outputs data like this:
![image](https://user-images.githubusercontent.com/1476795/121967757-8f3d0100-cd36-11eb-8b2e-f7537532133e.png)

2021-06-19 03:08 UTC, yuhc commented on generate.py
> +GSL_CFLAGS = ["-I" + os.path.dirname(os.path.realpath(sys.argv[0])) + "/third_party/GSL/include/"]
`+ "/third_party/GSL/include"]`

2021-06-19 03:08 UTC, yuhc commented on generate.py
> -        logger.info(f"ava-llvm downloaded to {download_target}")
Keep f strings.

2021-06-19 04:26 UTC, yuhc commented on generate.py
> +        logger.info("ava-llvm unpacked to {CLANG_LIB_DIR}")
Revert this line.

2021-06-20 18:58 UTC, yuhc requested changes

2021-06-20 18:58 UTC, yuhc commented on guestlib/queue_worker.h
> +class EXPORTED QueueWorker {
Should it be `CmdQueue`  and define in `common/cmd_queue.h`?
(API server may use the same interface to implement reply command queue in the future.)

2021-06-20 18:58 UTC, yuhc commented on guestlib/extensions/command_batch_worker.h
> +class CmdBatchingWorker : public QueueWorker {
`Worker` is a confusing naming, as the API server is also called "worker". Maybe `GeustCmdBatchingQueue: public CmdQueue`?

2021-06-22 03:07 UTC, yuhc approved these changes

2021-06-22 03:10 UTC, merged